dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0 
compiler:
  solc:
    remapping:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
dotenv: .env
networks:
  default: 'development'
  rinkeby:
    account: 'metamask'
    verify: True